[wokwi]
version = 1
firmware = '../../.pio/build/esp32-s3-devkitc-1/firmware.bin'
elf = '../../.pio/build/esp32-s3-devkitc-1/firmware.elf'

[[chip]]
name = "bc547-switch"
binary = "chips/bc547-switch.chip.wasm"
